Repository boostcamp-2020/Project02-A-RealTime-Translation-Messenger, pull requests merged in 2020-11, with the labels that each got.

#4 [BE] 백엔드 설정
  server/.eslintrc
  server/.prettierrc
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/src/loaders/index.ts
  server/src/models/.gitkeep
  server/src/routes/.gitkeep
  server/src/services/.gitkeep
  server/src/utils/.gitkeep
  server/tsconfig.json
Labels: 0_Merge: Dev-Web, Back-End 👨‍💻, Environment 🌏

#6 [Web] Fix backend environment
  server/.eslintrc
  server/package.json
Labels: Back-End 👨‍💻, Bug 🐞, Environment 🌏

#7 [Web] Configure client environment
  client/.babelrc
  client/.eslintrc
  client/.prettierrc
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/index.html
  client/src/index.tsx
  client/tsconfig.json
  client/webpack.config.js
Labels: 0_Merge: Dev-Web, Environment 🌏, Front-end 👩‍💻

#10 [Web] Fix root dir
  server/nodemon.json
  server/package-lock.json
  server/package.json
  server/tsconfig.json
Labels: Back-End 👨‍💻, Bug 🐞, Environment 🌏

#11 [Web] Fix webpack version
  client/package-lock.json
  client/package.json
Labels: Environment 🌏, Front-end 👩‍💻

#37 [Web] Initialize Express #35
  server/src/app.ts
  server/src/loaders/env.ts
  server/src/loaders/express.ts
  server/src/loaders/index.ts
  server/src/routes/.gitkeep
  server/src/routes/index.ts
Labels: 0_Merge: Dev-Web, Back-End 👨‍💻, Environment 🌏

#38 [iOS] Make up Chatting List UI
  iOS/Pupago/Pupago.xcodeproj/project.pbxproj
  iOS/Pupago/Pupago/Application/Navigator.swift
  iOS/Pupago/Pupago/Common/CollectionViewBaseCell.swift
  iOS/Pupago/Pupago/Module/Chatting List/ChattingListCell.swift
  iOS/Pupago/Pupago/Module/Chatting List/ChattingListViewController.swift
  iOS/Pupago/Pupago/Module/Chatting List/ChattingListViewModel.swift
  iOS/Pupago/Pupago/Module/Chatting/ChattingViewController.swift
  iOS/Pupago/Pupago/Module/Chatting/ChattingViewModel.swift
  iOS/Pupago/Pupago/Module/Create Chatroom/CreateRoomViewController.swift
  iOS/Pupago/Pupago/Module/Create Chatroom/CreateRoomViewModel.swift
  iOS/Pupago/Pupago/Module/Join Chatroom/JoinRoomViewController.swift
  iOS/Pupago/Pupago/Module/Join Chatroom/JoinRoomViewModel.swift
  iOS/Pupago/Pupago/Module/Main/Base.lproj/Main.storyboard
  iOS/Pupago/Pupago/Resource/Localize.swift
Labels: 0_Merge: Dev-iOS

#39 [Web] Connect Redis with Express
  server/package-lock.json
  server/package.json
  server/src/models/.gitkeep
  server/src/models/redisConnection.ts
  server/src/models/socketRoomModel.ts
Labels: 0_Merge: Dev-Web, Back-End 👨‍💻, Environment 🌏, Feature 🎨

#41 [Web] Configure Socket
  server/.prettierrc
  server/src/socket/socket.ts
  server/src/socket/socketController.ts
  server/src/types/socketTypes.ts
Labels: 0_Merge: Dev-Web, Back-End 👨‍💻, Feature 🎨

#42 [Web] Create databases models and declare functions
  server/src/models/roomInfoModel.ts
  server/src/models/roomSocketsInfoModel.ts
  server/src/models/socketRoomModel.ts
  server/src/types/databaseNames.ts
Labels: 0_Merge: Dev-Web, Back-End 👨‍💻, Feature 🎨

#43 [iOS] Make up Chatting Room UI
  iOS/Pupago/Pupago.xcodeproj/project.pbxproj
  iOS/Pupago/Pupago/Module/Chatting List/ChattingListViewModel.swift
  iOS/Pupago/Pupago/Module/Chatting/ChattingViewController.swift
  iOS/Pupago/Pupago/Module/Main/Base.lproj/Main.storyboard
  iOS/Pupago/Pupago/Resource/Assets.xcassets/RightSprinkle.imageset/Contents.json
  iOS/Pupago/Pupago/Resource/Assets.xcassets/RightSprinkle.imageset/Image.png
  iOS/Pupago/Pupago/Resource/Assets.xcassets/cancle.imageset/88-882904_mermaiden-crystal-dress-up-game-white-x-icon.png
  iOS/Pupago/Pupago/Resource/Assets.xcassets/cancle.imageset/Contents.json
  iOS/Pupago/Pupago/Resource/Assets.xcassets/iconNotification.imageset/Contents.json
  iOS/Pupago/Pupago/Resource/Assets.xcassets/iconNotification.imageset/iconNotification.png
  iOS/Pupago/Pupago/Resource/Assets.xcassets/iconNotification.imageset/iconNotification@2x.png
  iOS/Pupago/Pupago/Resource/Assets.xcassets/iconNotification.imageset/iconNotification@3x.png
  iOS/Pupago/Pupago/Resource/Assets.xcassets/leftSprinkle.imageset/Contents.json
  iOS/Pupago/Pupago/Resource/Assets.xcassets/leftSprinkle.imageset/Image.png
Labels: 0_Merge: Dev-iOS, iOS 🍎

#44 [Web] Change 'roomId' to 'roomCode'
  server/src/loaders/express.ts
  server/src/loaders/index.ts
  server/src/models/roomInfoModel.ts
  server/src/models/roomSocketsInfoModel.ts
  server/src/models/socketRoomModel.ts
  server/src/socket/socket.ts
  server/src/socket/socketController.ts
  server/src/types/socketTypes.ts
Labels: 0_Merge: Dev-Web, Back-End 👨‍💻, Refactor ⚙️

#47 [iOS] Implement Navigator Dismiss Function
  iOS/Pupago/Pupago.xcodeproj/project.pbxproj
  iOS/Pupago/Pupago/Application/Navigator.swift
  iOS/Pupago/Pupago/Common/ViewController.swift
  iOS/Pupago/Pupago/Module/Create Chatroom/CreateRoomViewController.swift
  iOS/Pupago/Pupago/Module/Create Chatroom/CreateRoomViewModel.swift
  iOS/Pupago/Pupago/Module/Join Chatroom/JoinRoomViewController.swift
  iOS/Pupago/Pupago/Module/Join Chatroom/JoinRoomViewModel.swift
  iOS/Pupago/Pupago/Module/Main/Base.lproj/Main.storyboard
Labels: 0_Merge: Dev-iOS, iOS 🍎

#46 [Web] Add 'isRoomEmpty' function and 'removeSocket' function in models
  server/src/models/roomInfoModel.ts
  server/src/models/roomSocketsInfoModel.ts
Labels: Back-End 👨‍💻, Feature 🎨

#48 [Web] Make socket models
  server/src/models/roomInfoModel.ts
  server/src/models/roomSocketsInfoModel.ts
  server/src/models/socketRoomModel.ts
Labels: 0_Merge: Dev-Web, Back-End 👨‍💻, Feature 🎨

#51 [iOS] Implement Chatting Room Function
  iOS/Pupago/Pupago/Module/Create Chatroom/CreateRoomViewController.swift
  iOS/Pupago/Pupago/Module/Create Chatroom/CreateRoomViewModel.swift
  iOS/Pupago/Pupago/Module/Main/Base.lproj/Main.storyboard
  iOS/Pupago/Pupago/Resource/Localize.swift
Labels: 0_Merge: Dev-iOS, iOS 🍎

#52 [iOS] Implement Join Chatting Room ViewModel
  iOS/Pupago/Pupago/Module/Join Chatroom/JoinRoomViewController.swift
  iOS/Pupago/Pupago/Module/Join Chatroom/JoinRoomViewModel.swift
  iOS/Pupago/Pupago/Module/Main/Base.lproj/Main.storyboard
  iOS/Pupago/Pupago/Resource/Localize.swift
Labels: 0_Merge: Dev-iOS

#50 [Web] Fix socket server port opening
  server/src/app.ts
  server/src/loaders/index.ts
  server/src/socket/socket.ts
Labels: 0_Merge: Dev-Web, Back-End 👨‍💻, Refactor ⚙️

#56 [iOS] HotFix for Week 2 Release
  iOS/Pupago/Pupago.xcodeproj/project.pbxproj
  iOS/Pupago/Pupago/Application/Application.swift
  iOS/Pupago/Pupago/Application/Navigator.swift
  iOS/Pupago/Pupago/Extensions/String+Regex.swift
  iOS/Pupago/Pupago/Module/Chatting List/ChattingListCell.swift
  iOS/Pupago/Pupago/Module/Chatting List/ChattingListViewController.swift
  iOS/Pupago/Pupago/Module/Chatting List/ChattingListViewModel.swift
  iOS/Pupago/Pupago/Module/Create Chatroom/CreateRoomViewController.swift
  iOS/Pupago/Pupago/Module/Create Chatroom/CreateRoomViewModel.swift
  iOS/Pupago/Pupago/Module/Join Chatroom/JoinRoomViewController.swift
  iOS/Pupago/Pupago/Module/Join Chatroom/JoinRoomViewModel.swift
  iOS/Pupago/Pupago/Module/Main/Base.lproj/Main.storyboard
  iOS/Pupago/Pupago/Module/Setting Language/LanguageViewController.swift
  iOS/Pupago/Pupago/Module/Setting Language/LanguageViewModel.swift
  iOS/Pupago/Pupago/Module/Setting Nickname/NicknameViewController.swift
  iOS/Pupago/Pupago/Module/Setting Nickname/NicknameViewModel.swift
  iOS/Pupago/Pupago/Resource/Assets.xcassets/logoSprinkle.imageset/Contents.json
  iOS/Pupago/Pupago/Resource/Assets.xcassets/logoSprinkle.imageset/logoSprinkle.png
  iOS/Pupago/Pupago/Resource/Assets.xcassets/logoline.imageset/Contents.json
  iOS/Pupago/Pupago/Resource/Assets.xcassets/logoline.imageset/logoline.png
  iOS/Pupago/Pupago/Util/RegexManager.swift
Labels: 0_Merge: Dev, HotFix 🖊, iOS 🍎

#57 [Web] Implement api and models for api
  server/package-lock.json
  server/package.json
  server/src/loaders/express.ts
  server/src/models/roomInfoModel.ts
  server/src/models/roomSocketsInfoModel.ts
  server/src/routes/index.ts
  server/src/routes/join.ts
  server/src/routes/room.ts
  server/src/types/socketTypes.ts
Labels: 0_Merge: Dev-Web, Back-End 👨‍💻, Feature 🎨

#58 [Web] Implement socket controller
  server/src/models/roomSocketsInfoModel.ts
  server/src/models/socketRoomModel.ts
  server/src/socket/socket.ts
  server/src/socket/socketController.ts
  server/src/types/socketTypes.ts
Labels: 0_Merge: Dev-Web, Back-End 👨‍💻, Feature 🎨

#59 [Web] Fix socket controller and flush database when server starts
  server/src/app.ts
  server/src/loaders/database.ts
  server/src/loaders/index.ts
  server/src/models/roomInfoModel.ts
  server/src/models/roomSocketsInfoModel.ts
  server/src/models/socketRoomModel.ts
  server/src/socket/socket.ts
  server/src/socket/socketController.ts
  server/src/types/socketTypes.ts
Labels: 0_Merge: Dev-Web, Back-End 👨‍💻, Feature 🎨

#60 [Web] Socket, API, Redis, Server and Client Environment setting
  client/.babelrc
  client/.eslintrc
  client/.prettierrc
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/index.html
  client/src/index.tsx
  client/tsconfig.json
  client/webpack.config.js
  server/.eslintrc
  server/.prettierrc
  server/nodemon.json
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/src/loaders/database.ts
  server/src/loaders/env.ts
  server/src/loaders/express.ts
  server/src/loaders/index.ts
  server/src/models/redisConnection.ts
  server/src/models/roomInfoModel.ts
  server/src/models/roomSocketsInfoModel.ts
  server/src/models/socketRoomModel.ts
  server/src/routes/index.ts
  server/src/routes/join.ts
  server/src/routes/room.ts
  server/src/services/.gitkeep
  server/src/socket/socket.ts
  server/src/socket/socketController.ts
  server/src/types/databaseNames.ts
  server/src/types/socketTypes.ts
  server/src/utils/.gitkeep
  server/tsconfig.json
Labels: 0_Merge: Dev

#69 [iOS] Implement Chatting UI
  iOS/Pupago/Podfile
  iOS/Pupago/Podfile.lock
  iOS/Pupago/Pupago.xcodeproj/project.pbxproj
  iOS/Pupago/Pupago/Common/Label.swift
  iOS/Pupago/Pupago/Common/StackView.swift
  iOS/Pupago/Pupago/Extensions/String+Regex.swift
  iOS/Pupago/Pupago/Model/Message.swift
  iOS/Pupago/Pupago/Module/Chatting/ChattingViewController.swift
  iOS/Pupago/Pupago/Module/Chatting/ChattingViewModel.swift
  iOS/Pupago/Pupago/Module/Chatting/MyChattingCell.swift
  iOS/Pupago/Pupago/Module/Chatting/OthersChattingCell.swift
  iOS/Pupago/Pupago/Module/Main/Base.lproj/Main.storyboard
Labels: 0_Merge: Dev-iOS, iOS 🍎

#62 [Web] Refactor Back-End
  server/src/app.ts
  server/src/loaders/database.ts
  server/src/loaders/express.ts
  server/src/loaders/index.ts
  server/src/models/roomInfoModel.ts
  server/src/routes/index.ts
  server/src/routes/join.ts
  server/src/routes/room.ts
  server/src/socket/socket.ts
  server/src/socket/socketController.ts
  server/src/socket/socketService.ts
  server/src/types/socketTypes.ts
  server/src/types/statusCode.ts
  server/src/utils/.gitkeep
  server/src/utils/date.ts
  server/src/utils/roomCode.ts
  server/src/utils/validation.ts
Labels: 0_Merge: Dev-Web, Back-End 👨‍💻, Refactor ⚙️

#80 [Web] Refactor api and rename directories and files
  server/src/@types/databaseName.ts
  server/src/@types/socketType.ts
  server/src/@types/statusCode.ts
  server/src/controllers/joinController.ts
  server/src/controllers/roomController.ts
  server/src/loaders/index.ts
  server/src/models/roomInfoModel.ts
  server/src/models/roomSocketsInfoModel.ts
  server/src/models/socketRoomModel.ts
  server/src/routes/join.ts
  server/src/routes/room.ts
  server/src/services/joinService.ts
  server/src/services/roomService.ts
  server/src/sockets/socket.ts
  server/src/sockets/socketController.ts
  server/src/sockets/socketService.ts
  server/src/types/statusCode.ts
  server/src/utils/date.ts
  server/src/utils/roomCode.ts
  server/src/utils/validation.ts
Labels: 0_Merge: Dev-Web, Back-End 👨‍💻, Refactor ⚙️

#82 [iOS] Construct Network layer & Add Mock data for rooms
  iOS/Pupago/Podfile
  iOS/Pupago/Podfile.lock
  iOS/Pupago/Pupago.xcodeproj/project.pbxproj
  iOS/Pupago/Pupago/Mock/MockAPI.swift
  iOS/Pupago/Pupago/Mock/MockEndpoint.swift
  iOS/Pupago/Pupago/Mock/room.json
  iOS/Pupago/Pupago/Model/Room.swift
  iOS/Pupago/Pupago/Module/Chatting List/ChattingListCell.swift
  iOS/Pupago/Pupago/Module/Chatting List/ChattingListViewController.swift
  iOS/Pupago/Pupago/Module/Chatting List/ChattingListViewModel.swift
  iOS/Pupago/Pupago/Network/Endpoint/RoomEndpoint.swift
  iOS/Pupago/Pupago/Network/EndpointType.swift
  iOS/Pupago/Pupago/Network/NetworkProviding.swift
  iOS/Pupago/Pupago/Network/Service/PupagoAPI.swift
Labels: 0_Merge: Dev-iOS

#81 [Web] change socket return value type to JSON string
  server/src/sockets/socketController.ts
Labels: 0_Merge: Dev-Web, Back-End 👨‍💻, Feature 🎨

#84 [Web] Refactor api endpoints and file names, and define enum error messages
  server/src/@types/dataType.ts
  server/src/@types/socketErrorMessage.ts
  server/src/@types/statusCode.ts
  server/src/controllers/joinController.ts
  server/src/controllers/roomController.ts
  server/src/loaders/express.ts
  server/src/models/roomInfoModel.ts
  server/src/routes/join.ts
  server/src/routes/room.ts
  server/src/services/joinService.ts
  server/src/services/roomService.ts
Labels: 0_Merge: Dev-Web, Back-End 👨‍💻, Feature 🎨, Refactor ⚙️

#85 [Web] Add validation to socket
  server/src/sockets/socket.ts
  server/src/sockets/socketController.ts
  server/src/sockets/socketService.ts
  server/src/utils/validation.ts
Labels: 0_Merge: Dev-Web, Back-End 👨‍💻, Feature 🎨

#87 [Web] Fix error handler in socketController file
  server/src/sockets/socketController.ts
Labels: 0_Merge: Dev-Web, Back-End 👨‍💻, Bug 🐞

#89 [Web] Fix error handler in socketController file
  server/src/sockets/socketController.ts
Labels: 0_Merge: Dev-Web, Back-End 👨‍💻, Bug 🐞

#90 [Web] Add deploy build script for server
  server/package.json
Labels: 0_Merge: Dev-Web, Back-End 👨‍💻, Environment 🌏
