Repository boostcamp-2020/Project02-A-RealTime-Translation-Messenger, pull requests merged in 2020-12, with the labels that each got.

#92 [iOS] Implement RxdataSource for Chat
  iOS/Pupago/Pupago/Module/Chatting/ChattingViewController.swift
  iOS/Pupago/Pupago/Module/Chatting/ChattingViewModel.swift
Labels: 0_Merge: Dev-iOS

#94 [iOS] Create isPrivated Segment Control
  iOS/Pupago/Pupago/Common/SegementedControl.swift
  iOS/Pupago/Pupago/Module/Main/Base.lproj/Main.storyboard
Labels: 0_Merge: Dev-iOS

#95 [iOS] Construct Network layer and Bind to ViewModel
  iOS/Pupago/Pupago/Mock/MockAPI.swift
  iOS/Pupago/Pupago/Mock/MockEndpoint.swift
  iOS/Pupago/Pupago/Model/Room.swift
  iOS/Pupago/Pupago/Module/Chatting List/ChattingListViewController.swift
  iOS/Pupago/Pupago/Module/Chatting List/ChattingListViewModel.swift
  iOS/Pupago/Pupago/Module/Create Chatroom/CreateRoomViewController.swift
  iOS/Pupago/Pupago/Module/Create Chatroom/CreateRoomViewModel.swift
  iOS/Pupago/Pupago/Module/Join Chatroom/JoinRoomViewController.swift
  iOS/Pupago/Pupago/Module/Join Chatroom/JoinRoomViewModel.swift
  iOS/Pupago/Pupago/Network/Endpoint/RoomEndpoint.swift
  iOS/Pupago/Pupago/Network/EndpointType.swift
  iOS/Pupago/Pupago/Network/NetworkProviding.swift
  iOS/Pupago/Pupago/Network/Service/PupagoAPI.swift
Labels: 0_Merge: Dev-iOS

#97 [Web]Architect front-end directory structure
  client/src/assets/.gitkeep
  client/src/components/atoms/.gitkeep
  client/src/components/molecules/.gitkeep
  client/src/components/organisms/.gitkeep
  client/src/hooks/.gitkeep
  client/src/pages/.gitkeep
  client/src/stores/.gitkeep
  client/src/utils/.gitkeep
Labels: 0_Merge: Dev-Web, Environment 🌏, Front-end 👩‍💻

#101 [Web] Install storybook
  client/.storybook/main.js
  client/.storybook/preview.js
  client/package-lock.json
  client/package.json
  client/src/stories/Button.stories.tsx
  client/src/stories/Button.tsx
  client/src/stories/Header.stories.tsx
  client/src/stories/Header.tsx
  client/src/stories/Introduction.stories.mdx
  client/src/stories/Page.stories.tsx
  client/src/stories/Page.tsx
  client/src/stories/assets/code-brackets.svg
  client/src/stories/assets/colors.svg
  client/src/stories/assets/comments.svg
  client/src/stories/assets/direction.svg
  client/src/stories/assets/flow.svg
  client/src/stories/assets/plugin.svg
  client/src/stories/assets/repo.svg
  client/src/stories/assets/stackalt.svg
  client/src/stories/button.css
  client/src/stories/header.css
  client/src/stories/page.css
Labels: Environment 🌏, Front-end 👩‍💻

#104 [Web] Downgrade socket.io and @types/socket.io
  server/package-lock.json
  server/package.json
  server/src/sockets/socket.ts
Labels: 0_Merge: Dev-Web, Back-End 👨‍💻, Bug 🐞

#102 [Web] Create MainButton component and story
  client/src/@types/Palette.ts
  client/src/components/MainButton.tsx
  client/src/stories/Button.stories.tsx
  client/src/stories/Button.tsx
  client/src/stories/Header.stories.tsx
  client/src/stories/Header.tsx
  client/src/stories/Introduction.stories.mdx
  client/src/stories/MainButton.stories.tsx
  client/src/stories/Page.stories.tsx
  client/src/stories/Page.tsx
  client/src/stories/button.css
  client/src/stories/header.css
  client/src/stories/page.css
Labels: 0_Merge: Dev-Web, Feature 🎨, Front-end 👩‍💻

#109 [Web] Install icon related modules
  client/package-lock.json
  client/package.json
Labels: 0_Merge: Dev-Web, Environment 🌏, Front-end 👩‍💻

#110 [Web] Apply global style related to font-family
  client/package-lock.json
  client/package.json
  client/src/App.tsx
Labels: 0_Merge: Dev-Web, Feature 🎨, Front-end 👩‍💻

#138 [Web] Create ChatBox component
  client/src/@types/Palette.ts
  client/src/components/atoms/ChatBox.tsx
  client/src/stories/ChatBox.stories.tsx
Labels: 0_Merge: Dev-Web, Feature 🎨, Front-end 👩‍💻

#134 [Web] Create MainPageBox component
  client/src/components/atoms/MainPageBox.tsx
  client/src/stories/MainPageBox.stories.tsx
Labels: Feature 🎨, Front-end 👩‍💻

#137 [Web] Create ProfileImage component and storybook
  client/src/components/atoms/ProfileImage.tsx
  client/src/stories/ProfileImage.stories.tsx
Labels: Feature 🎨, Front-end 👩‍💻

#133 [Web] create logo Components
  client/src/components/atoms/HomeLogo.tsx
  client/src/components/atoms/LogoWithText.tsx
  client/src/components/atoms/MainButton.tsx
  client/src/components/atoms/MiniLogo.tsx
  client/src/stories/HomeLogo.stories.tsx
  client/src/stories/LogoWithText.stories.tsx
  client/src/stories/MainButton.stories.tsx
  client/src/stories/MiniLogo.stories.tsx
Labels: 0_Merge: Dev-Web, Feature 🎨, Front-end 👩‍💻

#140 [Web] Create Background component
  client/src/@types/Palette.ts
  client/src/components/atoms/Background.tsx
  client/src/components/atoms/MainButton.tsx
  client/src/stories/Background.stories.tsx
Labels: 0_Merge: Dev-Web, Feature 🎨, Front-end 👩‍💻

#146 [Web] Create RoomItemBox component and stories
  client/src/components/atoms/RoomItemBox.tsx
  client/src/stories/RoomItemBox.stories.tsx
Labels: Feature 🎨, Front-end 👩‍💻

#141 [Web] Create LanguageSelectButton component
  client/src/components/atoms/LanguageSelectButton.tsx
  client/src/stories/LanguageSelectButton.stories.tsx
Labels: 0_Merge: Dev-Web, Feature 🎨, Front-end 👩‍💻

#145 [Web] Create CodeBox component and storybook
  client/src/components/atoms/CodeBox.tsx
  client/src/stories/CodeBox.stories.tsx
Labels: Feature 🎨, Front-end 👩‍💻

#147 [Web] Create ProfileChangeButton component and storybook
  client/src/components/atoms/ProfileChangeButton.tsx
  client/src/stories/ProfileChangeButton.stories.tsx
Labels: Feature 🎨, Front-end 👩‍💻

#153 [iOS] Construct Socket layer, bind to views
  iOS/Pupago/Podfile
  iOS/Pupago/Podfile.lock
  iOS/Pupago/Pupago.xcodeproj/project.pbxproj
  iOS/Pupago/Pupago/Application/Navigator.swift
  iOS/Pupago/Pupago/Extensions/SocketIO+Rx.swift
  iOS/Pupago/Pupago/Extensions/UIViewController+Rx.swift
  iOS/Pupago/Pupago/Info.plist
  iOS/Pupago/Pupago/Model/Message.swift
  iOS/Pupago/Pupago/Module/Chatting List/ChattingListViewController.swift
  iOS/Pupago/Pupago/Module/Chatting List/ChattingListViewModel.swift
  iOS/Pupago/Pupago/Module/Chatting/ChattingViewController.swift
  iOS/Pupago/Pupago/Module/Chatting/ChattingViewModel.swift
  iOS/Pupago/Pupago/Module/Chatting/MyChattingCell.swift
  iOS/Pupago/Pupago/Module/Chatting/OthersChattingCell.swift
  iOS/Pupago/Pupago/Module/Create Chatroom/CreateRoomViewController.swift
  iOS/Pupago/Pupago/Module/Create Chatroom/CreateRoomViewModel.swift
  iOS/Pupago/Pupago/Module/Main/Base.lproj/Main.storyboard
  iOS/Pupago/Pupago/Module/Setting Language/LanguageViewController.swift
  iOS/Pupago/Pupago/Module/Setting Language/LanguageViewModel.swift
  iOS/Pupago/Pupago/Module/Setting Nickname/NicknameViewController.swift
  iOS/Pupago/Pupago/Module/Setting Nickname/NicknameViewModel.swift
  iOS/Pupago/Pupago/Network/Endpoint/SocketEndpoint.swift
  iOS/Pupago/Pupago/Network/EndpointType.swift
  iOS/Pupago/Pupago/Network/NetworkProviding.swift
  iOS/Pupago/Pupago/Network/SocketManager.swift
  iOS/Pupago/Pupago/Resource/Localize.swift
  iOS/Pupago/Pupago/Util/DateManager.swift
Labels: 0_Merge: Dev-iOS, iOS 🍎

#132 [Web]Create Text Component
  client/src/components/atoms/.gitkeep
  client/src/components/atoms/Text.tsx
  client/src/stories/Text.stories.tsx
Labels: 0_Merge: Dev-Web, Feature 🎨, Front-end 👩‍💻

#135 [Web] Create UnderLinedInput component
  client/src/@types/Palette.ts
  client/src/components/atoms/UnderLinedInput.tsx
  client/src/stories/UnderLinedInput.stories.tsx
Labels: 0_Merge: Dev-Web, Feature 🎨, Front-end 👩‍💻

#139 [Web] Create SideBar Component
  client/src/components/atoms/SideBar.tsx
  client/src/stories/SideBar.stories.tsx
Labels: 0_Merge: Dev-Web, Feature 🎨, Front-end 👩‍💻

#143 [Web] Create SideBarTab component
  client/src/@types/Palette.ts
  client/src/components/atoms/SideBarTab.tsx
  client/src/stories/SideBarTab.stories.tsx
Labels: 0_Merge: Dev-Web, Feature 🎨, Front-end 👩‍💻

#144 [Web] Create IconButton component and stories
  client/src/components/atoms/IconButton.tsx
  client/src/stories/IconButton.stories.tsx
Labels: 0_Merge: Dev-Web, Feature 🎨, Front-end 👩‍💻

#148 [Web] Create voiceRecognition Component
  client/package-lock.json
  client/package.json
  client/src/components/atoms/VoiceRecognition.tsx
  client/src/stories/VoiceRecognition.stories.tsx
Labels: 0_Merge: Dev-Web, Feature 🎨, Front-end 👩‍💻

#149 [Web] Create CheckBox component and stories
  client/src/components/atoms/CheckBox.tsx
  client/src/stories/CheckBox.stories.tsx
Labels: 0_Merge: Dev-Web, Feature 🎨, Front-end 👩‍💻

#150 [Web] Create RefreshButton component and stories
  client/src/@types/Palette.ts
  client/src/components/atoms/RefreshButton.tsx
  client/src/stories/RefreshButton.stories.tsx
Labels: 0_Merge: Dev-Web, Feature 🎨, Front-end 👩‍💻

#154 [Web] Create ChatInput component
  client/src/@types/Palette.ts
  client/src/components/atoms/ChatInput.tsx
  client/src/stories/ChatInput.stories.tsx
Labels: 0_Merge: Dev-Web, Feature 🎨, Front-end 👩‍💻

#152 [Web] Create ParticipantNotification component
  client/src/@types/Palette.ts
  client/src/components/atoms/ParticipantNotification.tsx
  client/src/stories/ParticipantNotification.stories.tsx
Labels: 0_Merge: Dev-Web, Feature 🎨, Front-end 👩‍💻

#151 [Web] Create RoomCode component and storybook
  client/src/components/atoms/RoomCode.tsx
  client/src/stories/RoomCode.stories.tsx
Labels: 0_Merge: Dev-Web, Feature 🎨, Front-end 👩‍💻

#142 [Web] Create languageTag component and storybook
  client/src/components/atoms/LanguageTag.tsx
  client/src/stories/LanguageTag.stories.tsx
Labels: 0_Merge: Dev-Web, Feature 🎨, Front-end 👩‍💻

#156 [Web] Add missing props and options to the components
  client/src/App.tsx
  client/src/components/atoms/ChatBox.tsx
  client/src/components/atoms/ChatInput.tsx
  client/src/components/atoms/CodeBox.tsx
  client/src/components/atoms/HomeLogo.tsx
  client/src/components/atoms/IconButton.tsx
  client/src/components/atoms/LanguageSelectButton.tsx
  client/src/components/atoms/LanguageTag.tsx
  client/src/components/atoms/MainButton.tsx
  client/src/components/atoms/ProfileChangeButton.tsx
  client/src/components/atoms/RoomCode.tsx
  client/src/components/atoms/SideBar.tsx
  client/src/components/atoms/SideBarTab.tsx
  client/src/components/atoms/UnderLinedInput.tsx
  client/src/components/atoms/VoiceRecognition.tsx
  client/src/stories/IconButton.stories.tsx
Labels: 0_Merge: Dev-Web, Bug 🐞, Front-end 👩‍💻

#163 [iOS] Implement Keyboard Layout and Sending Chat UI
  iOS/Pupago/Pupago/Common/ViewController.swift
  iOS/Pupago/Pupago/Module/Chatting/ChattingViewController.swift
  iOS/Pupago/Pupago/Module/Chatting/ChattingViewModel.swift
  iOS/Pupago/Pupago/Module/Create Chatroom/CreateRoomViewController.swift
  iOS/Pupago/Pupago/Module/Join Chatroom/JoinRoomViewController.swift
  iOS/Pupago/Pupago/Module/Main/Base.lproj/Main.storyboard
  iOS/Pupago/Pupago/Module/Setting Nickname/NicknameViewController.swift
  iOS/Pupago/Pupago/Resource/Assets.xcassets/leftrain.imageset/Contents.json
  iOS/Pupago/Pupago/Resource/Assets.xcassets/leftrain.imageset/leftrain.png
  iOS/Pupago/Pupago/Resource/Assets.xcassets/rightrain.imageset/Contents.json
  iOS/Pupago/Pupago/Resource/Assets.xcassets/rightrain.imageset/rightrain.png
Labels: 0_Merge: Dev-iOS, iOS 🍎

#164 [iOS] Implement translation feature using Papago Api, bind to ChattingView
  iOS/Pupago/Pupago.xcodeproj/project.pbxproj
  iOS/Pupago/Pupago/Mock/MockEndpoint.swift
  iOS/Pupago/Pupago/Model/Language.swift
  iOS/Pupago/Pupago/Model/Translation.swift
  iOS/Pupago/Pupago/Module/Chatting/ChattingViewModel.swift
  iOS/Pupago/Pupago/Network/Endpoint/PapagoEndpoint.swift
  iOS/Pupago/Pupago/Network/Endpoint/RoomEndpoint.swift
  iOS/Pupago/Pupago/Network/EndpointType.swift
  iOS/Pupago/Pupago/Network/NetworkProviding.swift
  iOS/Pupago/Pupago/Network/Service/PupagoAPI.swift
  iOS/Pupago/Pupago/Network/SocketManager.swift
  iOS/Pupago/Pupago/Util/Translator.swift
Labels: 0_Merge: Dev-iOS, iOS 🍎

#165 [iOS] Implement Chatting UI, Socket, Translation, Keyboard Layout
  iOS/Pupago/Podfile
  iOS/Pupago/Podfile.lock
  iOS/Pupago/Pupago.xcodeproj/project.pbxproj
  iOS/Pupago/Pupago/Application/Navigator.swift
  iOS/Pupago/Pupago/Common/Label.swift
  iOS/Pupago/Pupago/Common/SegementedControl.swift
  iOS/Pupago/Pupago/Common/StackView.swift
  iOS/Pupago/Pupago/Common/ViewController.swift
  iOS/Pupago/Pupago/Extensions/SocketIO+Rx.swift
  iOS/Pupago/Pupago/Extensions/UIViewController+Rx.swift
  iOS/Pupago/Pupago/Info.plist
  iOS/Pupago/Pupago/Mock/MockAPI.swift
  iOS/Pupago/Pupago/Mock/MockEndpoint.swift
  iOS/Pupago/Pupago/Mock/room.json
  iOS/Pupago/Pupago/Model/Language.swift
  iOS/Pupago/Pupago/Model/Message.swift
  iOS/Pupago/Pupago/Model/Room.swift
  iOS/Pupago/Pupago/Model/Translation.swift
  iOS/Pupago/Pupago/Module/Chatting List/ChattingListCell.swift
  iOS/Pupago/Pupago/Module/Chatting List/ChattingListViewController.swift
  iOS/Pupago/Pupago/Module/Chatting List/ChattingListViewModel.swift
  iOS/Pupago/Pupago/Module/Chatting/ChattingViewController.swift
  iOS/Pupago/Pupago/Module/Chatting/ChattingViewModel.swift
  iOS/Pupago/Pupago/Module/Chatting/MyChattingCell.swift
  iOS/Pupago/Pupago/Module/Chatting/OthersChattingCell.swift
  iOS/Pupago/Pupago/Module/Create Chatroom/CreateRoomViewController.swift
  iOS/Pupago/Pupago/Module/Create Chatroom/CreateRoomViewModel.swift
  iOS/Pupago/Pupago/Module/Join Chatroom/JoinRoomViewController.swift
  iOS/Pupago/Pupago/Module/Join Chatroom/JoinRoomViewModel.swift
  iOS/Pupago/Pupago/Module/Main/Base.lproj/Main.storyboard
  iOS/Pupago/Pupago/Module/Setting Language/LanguageViewController.swift
  iOS/Pupago/Pupago/Module/Setting Language/LanguageViewModel.swift
  iOS/Pupago/Pupago/Module/Setting Nickname/NicknameViewController.swift
  iOS/Pupago/Pupago/Module/Setting Nickname/NicknameViewModel.swift
  iOS/Pupago/Pupago/Network/Endpoint/PapagoEndpoint.swift
  iOS/Pupago/Pupago/Network/Endpoint/RoomEndpoint.swift
  iOS/Pupago/Pupago/Network/Endpoint/SocketEndpoint.swift
  iOS/Pupago/Pupago/Network/EndpointType.swift
  iOS/Pupago/Pupago/Network/NetworkProviding.swift
  iOS/Pupago/Pupago/Network/Service/PupagoAPI.swift
  iOS/Pupago/Pupago/Network/SocketManager.swift
  iOS/Pupago/Pupago/Resource/Assets.xcassets/leftrain.imageset/Contents.json
  iOS/Pupago/Pupago/Resource/Assets.xcassets/leftrain.imageset/leftrain.png
  iOS/Pupago/Pupago/Resource/Assets.xcassets/rightrain.imageset/Contents.json
  iOS/Pupago/Pupago/Resource/Assets.xcassets/rightrain.imageset/rightrain.png
  iOS/Pupago/Pupago/Resource/Localize.swift
  iOS/Pupago/Pupago/Util/DateManager.swift
  iOS/Pupago/Pupago/Util/Translator.swift
Labels: 0_Merge: Dev, iOS 🍎

#172 [Web] Add api returning participants' list
  server/src/controllers/roomController.ts
  server/src/routes/room.ts
  server/src/sockets/socketController.ts
  server/src/sockets/socketService.ts
Labels: 0_Merge: Dev-Web, Back-End 👨‍💻, Feature 🎨

#187 [Web] Fix components' directory structure in stories
  client/src/stories/atoms/ChatBox.stories.tsx
  client/src/stories/atoms/ChatInput.stories.tsx
  client/src/stories/atoms/CheckBox.stories.tsx
  client/src/stories/atoms/CodeBox.stories.tsx
  client/src/stories/atoms/HomeLogo.stories.tsx
  client/src/stories/atoms/IconButton.stories.tsx
  client/src/stories/atoms/LanguageSelectButton.stories.tsx
  client/src/stories/atoms/LanguageTag.stories.tsx
  client/src/stories/atoms/LogoWithText.stories.tsx
  client/src/stories/atoms/MainButton.stories.tsx
  client/src/stories/atoms/MainPageBox.stories.tsx
  client/src/stories/atoms/MiniLogo.stories.tsx
  client/src/stories/atoms/ParticipantNotification.stories.tsx
  client/src/stories/atoms/ProfileChangeButton.stories.tsx
  client/src/stories/atoms/ProfileImage.stories.tsx
  client/src/stories/atoms/RefreshButton.stories.tsx
  client/src/stories/atoms/RoomCode.stories.tsx
  client/src/stories/atoms/RoomItemBox.stories.tsx
  client/src/stories/atoms/SideBar.stories.tsx
  client/src/stories/atoms/SideBarTab.stories.tsx
  client/src/stories/atoms/Text.stories.tsx
  client/src/stories/atoms/UnderLinedInput.stories.tsx
  client/src/stories/atoms/VoiceRecognition.stories.tsx
Labels: Bug 🐞, Front-end 👩‍💻

#188 [iOS] Bind realtime translation view, sync flush timing
  iOS/Pupago/Pupago.xcodeproj/project.pbxproj
  iOS/Pupago/Pupago/Extensions/UITextView+Binder.swift
  iOS/Pupago/Pupago/Module/Chatting/ChattingViewController.swift
  iOS/Pupago/Pupago/Module/Chatting/ChattingViewModel.swift
  iOS/Pupago/Pupago/Module/Chatting/MessageDataSource.swift
  iOS/Pupago/Pupago/Module/Chatting/MyChattingCell.swift
  iOS/Pupago/Pupago/Module/Chatting/OthersChattingCell.swift
  iOS/Pupago/Pupago/Module/Main/Base.lproj/Main.storyboard
  iOS/Pupago/Pupago/Network/NetworkProviding.swift
  iOS/Pupago/Pupago/Util/Translator.swift
Labels: 0_Merge: Dev-iOS

#192 [Web] Refactor atoms' markup and some code
  client/src/components/atoms/boxes/ChatBox.tsx
  client/src/components/atoms/boxes/CheckBox.tsx
  client/src/components/atoms/boxes/CodeBox.tsx
  client/src/components/atoms/boxes/MainPageBox.tsx
  client/src/components/atoms/boxes/RoomItemBox.tsx
  client/src/components/atoms/boxes/SideBar.tsx
  client/src/components/atoms/buttons/IconButton.tsx
  client/src/components/atoms/buttons/MainButton.tsx
  client/src/components/atoms/buttons/ProfileChangeButton.tsx
  client/src/components/atoms/buttons/RefreshButton.tsx
  client/src/components/atoms/buttons/SideBarTab.tsx
  client/src/components/atoms/inputs/ChatInput.tsx
  client/src/components/atoms/inputs/UnderLinedInput.tsx
  client/src/components/atoms/resources/LanguageTag.tsx
  client/src/components/atoms/resources/ProfileImage.tsx
  client/src/components/atoms/resources/VoiceRecognition.tsx
  client/src/components/atoms/texts/ParticipantNotification.tsx
  client/src/components/atoms/texts/RoomCode.tsx
  client/src/components/atoms/texts/Text.tsx
Labels: 0_Merge: Dev-Web, Front-end 👩‍💻, Refactor ⚙️

#196 [iOS] Make up Participants list UI, Implement related viewmodel
  iOS/Pupago/Pupago.xcodeproj/project.pbxproj
  iOS/Pupago/Pupago/Application/Navigator.swift
  iOS/Pupago/Pupago/Common/SlideInTransition.swift
  iOS/Pupago/Pupago/Model/Participant.swift
  iOS/Pupago/Pupago/Module/Chatting/ChattingViewController.swift
  iOS/Pupago/Pupago/Module/Chatting/ChattingViewModel.swift
  iOS/Pupago/Pupago/Module/Main/Base.lproj/Main.storyboard
  iOS/Pupago/Pupago/Module/Participant/ParticipantCell.swift
  iOS/Pupago/Pupago/Module/Participant/ParticipantViewController.swift
  iOS/Pupago/Pupago/Module/Participant/ParticipantViewModel.swift
  iOS/Pupago/Pupago/Network/Endpoint/RoomEndpoint.swift
  iOS/Pupago/Pupago/Network/Service/PupagoAPI.swift
  iOS/Pupago/Pupago/Util/TransitionHelper.swift
Labels: 0_Merge: Dev-iOS, iOS 🍎

#195 [Web] Downgrade socket.io-client to v1.4.8 #194
  client/package-lock.json
  client/package.json
Labels: Environment 🌏, Front-end 👩‍💻

#197 [Web] Change atoms' stories folder to pupagoAtom
  client/src/stories/atoms/Background.stories.tsx
  client/src/stories/atoms/ChatBox.stories.tsx
  client/src/stories/atoms/ChatInput.stories.tsx
  client/src/stories/atoms/CheckBox.stories.tsx
  client/src/stories/atoms/CodeBox.stories.tsx
  client/src/stories/atoms/HomeLogo.stories.tsx
  client/src/stories/atoms/IconButton.stories.tsx
  client/src/stories/atoms/LanguageSelectButton.stories.tsx
  client/src/stories/atoms/LanguageTag.stories.tsx
  client/src/stories/atoms/LogoWithText.stories.tsx
  client/src/stories/atoms/MainButton.stories.tsx
  client/src/stories/atoms/MainPageBox.stories.tsx
  client/src/stories/atoms/MiniLogo.stories.tsx
  client/src/stories/atoms/ParticipantNotification.stories.tsx
  client/src/stories/atoms/ProfileChangeButton.stories.tsx
  client/src/stories/atoms/ProfileImage.stories.tsx
  client/src/stories/atoms/RefreshButton.stories.tsx
  client/src/stories/atoms/RoomCode.stories.tsx
  client/src/stories/atoms/RoomItemBox.stories.tsx
  client/src/stories/atoms/SideBar.stories.tsx
  client/src/stories/atoms/SideBarTab.stories.tsx
  client/src/stories/atoms/Text.stories.tsx
  client/src/stories/atoms/UnderLinedInput.stories.tsx
  client/src/stories/atoms/VoiceRecognition.stories.tsx
Labels: Front-end 👩‍💻, Refactor ⚙️, Test :test_tube:

#198 [Web] Create RoomItem molecule
  client/src/components/atoms/boxes/RoomItemBox.tsx
  client/src/components/atoms/texts/Text.tsx
  client/src/components/molecules/common/RoomItem.tsx
  client/src/stories/molecules/RoomItemType.stories.tsx
Labels: Feature 🎨, Front-end 👩‍💻

#193 [Web] add API for getting random profile image and add related logics in the socket files
  server/package-lock.json
  server/package.json
  server/src/@types/dataType.ts
  server/src/@types/socketErrorMessage.ts
  server/src/controllers/profileImageController.ts
  server/src/routes/index.ts
  server/src/routes/profileImage.ts
  server/src/services/.gitkeep
  server/src/services/profileImageService.ts
  server/src/sockets/socketController.ts
  server/src/sockets/socketService.ts
  server/src/utils/validation.ts
Labels: Back-End 👨‍💻, Feature 🎨

#199 [Web] Change api endpoint returning participants' list
  server/src/routes/room.ts
Labels: 0_Merge: Dev-Web, Back-End 👨‍💻, Bug 🐞

#212 [Web] Create CryingPapago component and stories
  client/src/components/atoms/resources/CryingPapago.tsx
  client/src/stories/atoms/CryingPapago.stories.tsx
Labels: Feature 🎨, Front-end 👩‍💻

#201 [Web] Add ChatModalBox component and stories
  client/src/components/atoms/boxes/ChatModalBox.tsx
  client/src/stories/atoms/ChatModalBox.stories.tsx
Labels: Feature 🎨, Front-end 👩‍💻

#200 [Web] Create ChatRoomHeader molecule
  client/src/components/atoms/buttons/IconButton.tsx
  client/src/components/atoms/texts/RoomCode.tsx
  client/src/components/molecules/chatRoomPages/ChatRoomHeader.tsx
  client/src/stories/molecules/ChatRoomHeader.stories.tsx
Labels: Feature 🎨, Front-end 👩‍💻

#202 [Web] add MainTitle component and stories
  client/src/components/molecules/.gitkeep
  client/src/components/molecules/MainPage/MainTitle.tsx
  client/src/stories/molecules/.gitkeep
  client/src/stories/molecules/MainTitle.stories.tsx
Labels: 0_Merge: Dev-Web, Feature 🎨, Front-end 👩‍💻

#203 [Web] Create ProfilePictureSelection molecule and storybook
  client/src/components/molecules/mainPage/ProfilePictureSelection.tsx
  client/src/stories/molecules/ProfilePictureSelection.stories.tsx
Labels: 0_Merge: Dev-Web, Feature 🎨, Front-end 👩‍💻

#204 [Web] Create ChatItem molecule
  client/src/components/atoms/boxes/ChatBox.tsx
  client/src/components/molecules/chatRoomPage/ChatItem.tsx
  client/src/stories/molecules/ChatItem.stories.tsx
Labels: Feature 🎨, Front-end 👩‍💻

#206 [Web] Create RoomCreation molecule and stories
  client/src/components/atoms/inputs/UnderLinedInput.tsx
  client/src/components/molecules/RoomCreationPage/RoomCreation.tsx
  client/src/stories/molecules/RoomCreation.stories.tsx
Labels: 0_Merge: Dev-Web, Feature 🎨, Front-end 👩‍💻

#207 [Web] Create SideBar molecule
  client/src/components/atoms/buttons/SideBarTab.tsx
  client/src/components/molecules/chatRoomPage/SideBar.tsx
  client/src/stories/molecules/SideBar.stories.tsx
Labels: 0_Merge: Dev-Web, Feature 🎨, Front-end 👩‍💻

#205 [Web] Add color white for disabled undefined #99
  client/src/components/atoms/buttons/MainButton.tsx
  client/src/stories/atoms/MainButton.stories.tsx
Labels: 0_Merge: Dev-Web, Feature 🎨, Front-end 👩‍💻

#208 [Web] Create ParticipantItem molecule and stories
  client/src/components/molecules/ChatRoomPage/ParticipantItem.tsx
  client/src/stories/molecules/ParticipantItem.stories.tsx
Labels: 0_Merge: Dev-Web, Feature 🎨, Front-end 👩‍💻

#211 [Web] Create MyProfile molecule and storybook
  client/src/components/molecules/roomListPage/MyProfile.tsx
  client/src/stories/molecules/MyProfile.stories.tsx
Labels: 0_Merge: Dev-Web, Feature 🎨, Front-end 👩‍💻

#213 [Web] Create ParticipantCount molecule and story
  client/src/components/molecules/ChatRoomPage/ParticipantCount.tsx
  client/src/stories/molecules/ParticipantCount.stories.tsx
Labels: 0_Merge: Dev-Web, Feature 🎨, Front-end 👩‍💻

#209 [Web] Create ChatInput molecule
  client/src/@types/Palette.ts
  client/src/components/atoms/buttons/IconButton.tsx
  client/src/components/molecules/chatRoomPage/ChatInput.tsx
  client/src/stories/molecules/ChatInput.stories.tsx
Labels: 0_Merge: Dev-Web, Feature 🎨, Front-end 👩‍💻

#216 Rename folders' name in molecules folder
  client/src/components/molecules/ChatRoomPage/ChatRoomHeader.tsx
  client/src/stories/molecules/ChatRoomHeader.stories.tsx
  client/src/stories/molecules/MainTitle.stories.tsx
  client/src/stories/molecules/ParticipantCount.stories.tsx
  client/src/stories/molecules/ParticipantItem.stories.tsx
  client/src/stories/molecules/RoomCreation.stories.tsx
Labels: 0_Merge: Dev-Web, Front-end 👩‍💻, Refactor ⚙️

#214 [Web] Create ChatModalBackground component and stories
  client/src/components/atoms/boxes/ChatModalBackground.tsx
  client/src/stories/atoms/ChatModalBackground.stories.tsx
Labels: 0_Merge: Dev-Web, Feature 🎨, Front-end 👩‍💻

#210 [Web] Create LanguageSelection molecule and storybook
  client/src/components/molecules/mainPage/LanguageSelection.tsx
  client/src/stories/molecules/LanguageSelection.stories.tsx
Labels: 0_Merge: Dev-Web, Feature 🎨, Front-end 👩‍💻

#218 [Web] Apply global style to storybook
  client/.storybook/preview.js
  client/src/App.tsx
Labels: 0_Merge: Dev-Web, Environment 🌏, Front-end 👩‍💻

#220 [Web] Create CodeInput molecule and story
  client/src/components/molecules/codeInputPage/CodeInput.tsx
  client/src/stories/molecules/CodeInput.stories.tsx
Labels: 0_Merge: Dev-Web, Feature 🎨, Front-end 👩‍💻

#225 [Web] Create VoiceRecognitionModal molecule and story
  client/src/components/molecules/ChatRoomPage/VoiceRecognitionModal.tsx
  client/src/stories/molecules/VoiceRecognitionModal.stories.tsx
Labels: 0_Merge: Dev-Web, Feature 🎨, Front-end 👩‍💻

#221 [Web] Create RoomSwitchModal molecule and story
  client/src/components/atoms/boxes/ChatModalBackground.tsx
  client/src/components/atoms/boxes/ChatModalBox.tsx
  client/src/components/molecules/ChatRoomPage/RoomSwitchModal.tsx
  client/src/stories/atoms/ChatModalBackground.stories.tsx
  client/src/stories/molecules/RoomSwitchModal.stories.tsx
Labels: 0_Merge: Dev-Web, Feature 🎨, Front-end 👩‍💻

#226 [Web] Fix language selection method
  client/src/components/molecules/mainPage/LanguageSelection.tsx
  client/src/stories/molecules/LanguageSelection.stories.tsx
Labels: 0_Merge: Dev-Web, Bug 🐞, Front-end 👩‍💻

#219 [Web] Create NoChatRoom molecule and storybook
  client/src/components/molecules/roomListPage/NoChatRoom.tsx
  client/src/stories/molecules/NoChatRoom.stories.tsx
Labels: 0_Merge: Dev-Web, Feature 🎨, Front-end 👩‍💻

#228 [Web] Refactor and fix molecules
  client/src/components/atoms/boxes/RoomItemBox.tsx
  client/src/components/atoms/boxes/SideBarBox.tsx
  client/src/components/atoms/resources/ProfileImage.tsx
  client/src/components/molecules/ChatRoomPage/ParticipantCount.tsx
  client/src/components/molecules/ChatRoomPage/ParticipantItem.tsx
  client/src/components/molecules/MainPage/MainTitle.tsx
  client/src/components/molecules/RoomCreationPage/RoomCreation.tsx
  client/src/components/molecules/chatRoomPage/SideBar.tsx
  client/src/components/molecules/common/RoomItem.tsx
  client/src/components/molecules/mainPage/LanguageSelection.tsx
  client/src/components/molecules/mainPage/ProfilePictureSelection.tsx
  client/src/components/molecules/roomListPage/MyProfile.tsx
  client/src/stories/atoms/SideBar.stories.tsx
Labels: 0_Merge: Dev-Web, Front-end 👩‍💻, Refactor ⚙️

#230 [Web] Init Redux, Redux-thunk
  client/package-lock.json
  client/package.json
  client/src/index.tsx
  client/src/modules/index.ts
  client/src/stores/.gitkeep
Labels: 0_Merge: Dev-Web, Environment 🌏, Front-end 👩‍💻

#233 [Web] add API for getting random profile image and add related logics in the socket files
  server/package-lock.json
  server/package.json
  server/src/@types/dataType.ts
  server/src/@types/socketErrorMessage.ts
  server/src/controllers/profileImageController.ts
  server/src/routes/index.ts
  server/src/routes/profileImage.ts
  server/src/services/.gitkeep
  server/src/services/profileImageService.ts
  server/src/sockets/socketController.ts
  server/src/sockets/socketService.ts
  server/src/utils/validation.ts
Labels: 0_Merge: Dev-Web, Back-End 👨‍💻, Feature 🎨

#232 Revert "[Web] add API for getting random profile image and add related logics in the socket files"
  server/package-lock.json
  server/package.json
  server/src/@types/dataType.ts
  server/src/@types/socketErrorMessage.ts
  server/src/controllers/profileImageController.ts
  server/src/routes/index.ts
  server/src/routes/profileImage.ts
  server/src/services/.gitkeep
  server/src/services/profileImageService.ts
  server/src/sockets/socketController.ts
  server/src/sockets/socketService.ts
  server/src/utils/validation.ts
Labels: 0_Merge: Dev, Back-End 👨‍💻, Bug 🐞

#236 [Web] Create roomList module
  client/.babelrc
  client/package-lock.json
  client/package.json
  client/src/@types/types.ts
  client/src/assets/api.ts
  client/src/components/atoms/boxes/SideBarBox.tsx
  client/src/modules/index.ts
  client/src/modules/roomList.ts
  client/webpack.config.js
Labels: 0_Merge: Dev-Web, Bug 🐞, Environment 🌏, Feature 🎨, Front-end 👩‍💻

#238 [Web] Add diffNickname to 'receive particpants list' socket event
  server/src/sockets/socketController.ts
Labels: 0_Merge: Dev-Web, Back-End 👨‍💻, Feature 🎨

#239 [Web] Refactor Redux module to Redux-toolkit
  client/package-lock.json
  client/package.json
  client/src/modules/roomList.ts
Labels: Front-end 👩‍💻, Refactor ⚙️

#231 [iOS] Implement Speech To Text Layout and UI
  iOS/Pupago/Pupago.xcodeproj/project.pbxproj
  iOS/Pupago/Pupago/Application/Navigator.swift
  iOS/Pupago/Pupago/Info.plist
  iOS/Pupago/Pupago/Module/Chatting List/ChattingListViewController.swift
  iOS/Pupago/Pupago/Module/Chatting/ChattingViewController.swift
  iOS/Pupago/Pupago/Module/Chatting/ChattingViewModel.swift
  iOS/Pupago/Pupago/Module/Main/Base.lproj/Main.storyboard
  iOS/Pupago/Pupago/Module/Participant/ParticipantCell.swift
  iOS/Pupago/Pupago/Module/Participant/ParticipantViewController.swift
  iOS/Pupago/Pupago/Module/SpeechToText/SpeechViewController.swift
  iOS/Pupago/Pupago/Module/SpeechToText/SpeechViewModel.swift
  iOS/Pupago/Pupago/Network/Endpoint/RoomEndpoint.swift
  iOS/Pupago/Pupago/Network/SocketManager.swift
  iOS/Pupago/Pupago/Resource/Assets.xcassets/miced.imageset/Contents.json
  iOS/Pupago/Pupago/Resource/Assets.xcassets/miced.imageset/miced.png
  iOS/Pupago/Pupago/Resource/Assets.xcassets/micing.imageset/Contents.json
  iOS/Pupago/Pupago/Resource/Assets.xcassets/micing.imageset/micing.png
  iOS/Pupago/Pupago/Resource/Localize.swift
  iOS/Pupago/Pupago/Util/SpeechManager.swift
Labels: 0_Merge: Dev-iOS, iOS 🍎

#243 [Web] Fix createReceiveChatType because of imageUrl
  server/src/@types/dataType.ts
Labels: 0_Merge: Dev-Web, Back-End 👨‍💻, Bug 🐞

#244 [Web] add ChatPage component and socket connection & events
  client/package-lock.json
  client/package.json
  client/src/@types/types.ts
  client/src/pages/ChatPage.tsx
Labels: 0_Merge: Dev-Web, Environment 🌏, Feature 🎨, Front-end 👩‍💻

#245 [Web] Fix createReceiveChatType
  server/src/sockets/socketService.ts
Labels: 0_Merge: Dev-Web, Back-End 👨‍💻, Feature 🎨

#246 [Web] Change RoomListInitialStateType
  client/src/modules/roomList.ts
Labels: 0_Merge: Dev-Web, Front-end 👩‍💻, Refactor ⚙️

#241 [iOS] Implement Participant Status and Profile Image
  iOS/Pupago/Podfile
  iOS/Pupago/Podfile.lock
  iOS/Pupago/Pupago.xcodeproj/project.pbxproj
  iOS/Pupago/Pupago/Application/Application.swift
  iOS/Pupago/Pupago/Model/Message.swift
  iOS/Pupago/Pupago/Model/Participant.swift
  iOS/Pupago/Pupago/Model/Profile.swift
  iOS/Pupago/Pupago/Module/Chatting List/ChattingListViewController.swift
  iOS/Pupago/Pupago/Module/Chatting List/ChattingListViewModel.swift
  iOS/Pupago/Pupago/Module/Chatting/ChattingViewController.swift
  iOS/Pupago/Pupago/Module/Chatting/ChattingViewModel.swift
  iOS/Pupago/Pupago/Module/Chatting/OthersChattingCell.swift
  iOS/Pupago/Pupago/Module/Main/Base.lproj/Main.storyboard
  iOS/Pupago/Pupago/Module/Participant/ParticipantCell.swift
  iOS/Pupago/Pupago/Module/Participant/ParticipantViewController.swift
  iOS/Pupago/Pupago/Module/Participant/ParticipantViewModel.swift
  iOS/Pupago/Pupago/Module/Setting Nickname/NicknameViewModel.swift
  iOS/Pupago/Pupago/Network/Endpoint/RoomEndpoint.swift
  iOS/Pupago/Pupago/Network/Service/PupagoAPI.swift
  iOS/Pupago/Pupago/Network/SocketManager.swift
  iOS/Pupago/Pupago/Resource/Localize.swift
Labels: 0_Merge: Dev-iOS

#256 [Web] Create papago api
  server/package-lock.json
  server/package.json
  server/src/controllers/papagoController.ts
  server/src/routes/index.ts
  server/src/routes/papago.ts
Labels: 0_Merge: Dev-Web, Back-End 👨‍💻, Feature 🎨

#250 [Web] Add onRoomList custom hook and change RoomListInitialStateType to InitialStateType
  client/src/hooks/.gitkeep
  client/src/hooks/useRoomList.tsx
  client/src/modules/roomList.ts
Labels: 0_Merge: Dev-Web, Front-end 👩‍💻, Refactor ⚙️

#253 [Web] Create participantsList module
  client/src/hooks/useParticipantsList.tsx
  client/src/modules/index.ts
  client/src/modules/participantsList.ts
Labels: 0_Merge: Dev-Web, Feature 🎨, Front-end 👩‍💻

#257 [Web] Update webpack to handle dotenv and set BASE_URL
  client/webpack.config.js
Labels: 0_Merge: Dev-Web, Environment 🌏, Front-end 👩‍💻

#249 [Web] Create user module
  client/src/@types/types.ts
  client/src/hooks/useUser.tsx
  client/src/modules/index.ts
  client/src/modules/user.ts
Labels: 0_Merge: Dev-Web, Feature 🎨, Front-end 👩‍💻

#262 [Web] Change position of the libraries line
  client/src/hooks/useParticipantsList.tsx
  client/src/modules/participantsList.ts
Labels: 0_Merge: Dev-Web, Front-end 👩‍💻, Refactor ⚙️

#261 [Web] Implement ChatInput module, custom hook, debounce
  client/src/@types/langCode.ts
  client/src/@types/types.ts
  client/src/assets/api.ts
  client/src/hooks/useChatInput.tsx
  client/src/modules/chatInput.ts
  client/src/modules/index.ts
  client/src/utils/langCode.ts
Labels: 0_Merge: Dev-Web, Feature 🎨, Front-end 👩‍💻

#254 [Web] Create chat module
  client/src/@types/types.ts
  client/src/hooks/useChat.tsx
  client/src/modules/chat.ts
  client/src/modules/index.ts
Labels: 0_Merge: Dev-Web, Feature 🎨, Front-end 👩‍💻

#258 [Web] Create room module and custom hook
  client/src/@types/types.ts
  client/src/assets/api.ts
  client/src/hooks/useRoom.tsx
  client/src/modules/index.ts
  client/src/modules/room.ts
Labels: 0_Merge: Dev-Web, Feature 🎨, Front-end 👩‍💻

#264 [Web] Fix wrong resolve while merge redux modules
  client/src/App.tsx
  client/src/assets/api.ts
Labels: 0_Merge: Dev-Web, Bug 🐞

#267 [Web] Add routing to the client
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/index.tsx
  client/src/pages/ChatPage.tsx
  client/src/pages/MainPage.tsx
Labels: Feature 🎨, Front-end 👩‍💻

#265 [iOS] Implement Setup Animation and Update Description
  iOS/Pupago/Podfile
  iOS/Pupago/Podfile.lock
  iOS/Pupago/Pupago/Common/ValidatingTextField.swift
  iOS/Pupago/Pupago/Module/Main/Base.lproj/Main.storyboard
  iOS/Pupago/Pupago/Module/Setting Language/LanguageViewController.swift
  iOS/Pupago/Pupago/Module/Setting Nickname/NicknameViewController.swift
  iOS/Pupago/Pupago/Module/Setting Nickname/NicknameViewModel.swift
  iOS/Pupago/Pupago/Resource/Assets.xcassets/arrow.imageset/Contents.json
  iOS/Pupago/Pupago/Resource/Assets.xcassets/arrow.imageset/arrow.png
  iOS/Pupago/Pupago/Resource/Assets.xcassets/arrowed.imageset/Contents.json
  iOS/Pupago/Pupago/Resource/Assets.xcassets/arrowed.imageset/arrowed.png
  iOS/Pupago/Pupago/Resource/Assets.xcassets/miced.imageset/miced.png
  iOS/Pupago/Pupago/Resource/Assets.xcassets/micing.imageset/micing.png
  iOS/Pupago/Pupago/Resource/Localize.swift
Labels: 0_Merge: Dev-iOS, iOS 🍎

#268 [iOS] Implement Speech Assist UI and Add Localize
  iOS/Pupago/Pupago/Application/Navigator.swift
  iOS/Pupago/Pupago/Module/Chatting/ChattingViewController.swift
  iOS/Pupago/Pupago/Module/Main/Base.lproj/Main.storyboard
  iOS/Pupago/Pupago/Module/SpeechToText/SpeechViewController.swift
  iOS/Pupago/Pupago/Module/SpeechToText/SpeechViewModel.swift
  iOS/Pupago/Pupago/Resource/Localize.swift
Labels: 0_Merge: Dev-iOS, iOS 🍎

#271 [Web] Create MainPage, userInfoPage's skeleton
  client/src/@types/types.ts
  client/src/App.tsx
  client/src/assets/api.ts
  client/src/components/atoms/boxes/MainPageBox.tsx
  client/src/components/atoms/buttons/MainButton.tsx
  client/src/components/atoms/inputs/UnderLinedInput.tsx
  client/src/components/atoms/resources/Background.tsx
  client/src/components/atoms/resources/ProfileImage.tsx
  client/src/components/molecules/userInfoPage/LanguageSelection.tsx
  client/src/components/molecules/userInfoPage/MainTitle.tsx
  client/src/components/molecules/userInfoPage/ProfilePictureSelection.tsx
  client/src/components/organisms/userInfoPage/LanguageSelection.tsx
  client/src/components/organisms/userInfoPage/NicknameInput.tsx
  client/src/components/organisms/userInfoPage/ProfilePictureSelection.tsx
  client/src/components/organisms/userInfoPage/StartButtons.tsx
  client/src/hooks/useUser.tsx
  client/src/modules/user.ts
  client/src/pages/MainPage.tsx
  client/src/pages/UserInfoPage.tsx
  client/src/stories/atoms/Background.stories.tsx
  client/src/stories/molecules/LanguageSelection.stories.tsx
  client/src/stories/molecules/MainTitle.stories.tsx
  client/src/stories/molecules/ProfilePictureSelection.stories.tsx
Labels: 0_Merge: Dev-Web, Feature 🎨, Front-end 👩‍💻

#272 [iOS] Implement Chatting Clipboard and Toaster
  iOS/Pupago/Pupago/Common/ValidatingTextField.swift
  iOS/Pupago/Pupago/Common/ViewController.swift
  iOS/Pupago/Pupago/Module/Chatting List/ChattingListViewController.swift
  iOS/Pupago/Pupago/Module/Chatting/ChattingViewController.swift
  iOS/Pupago/Pupago/Module/Chatting/ChattingViewModel.swift
  iOS/Pupago/Pupago/Module/Join Chatroom/JoinRoomViewModel.swift
  iOS/Pupago/Pupago/Module/Main/Base.lproj/Main.storyboard
  iOS/Pupago/Pupago/Module/SpeechToText/SpeechViewController.swift
  iOS/Pupago/Pupago/Resource/Localize.swift
Labels: 0_Merge: Dev-iOS

#273 [iOS] Implement Refresh control, Update image management using KingFisher
  iOS/Pupago/.swiftlint.yml
  iOS/Pupago/Pupago.xcodeproj/project.pbxproj
  iOS/Pupago/Pupago/Common/ValidatingTextField.swift
  iOS/Pupago/Pupago/Extensions/KingFisher+Rx.swift
  iOS/Pupago/Pupago/Module/Chatting List/ChattingListViewController.swift
  iOS/Pupago/Pupago/Module/Chatting List/ChattingListViewModel.swift
  iOS/Pupago/Pupago/Module/Main/Base.lproj/Main.storyboard
Labels: 0_Merge: Dev-iOS

#284 [iOS] Import Lottie, make up check animation view, and apply
  iOS/Pupago/Podfile
  iOS/Pupago/Podfile.lock
  iOS/Pupago/Pupago.xcodeproj/project.pbxproj
  iOS/Pupago/Pupago/Common/ViewController.swift
  iOS/Pupago/Pupago/Module/Setting Language/LanguageViewController.swift
  iOS/Pupago/Pupago/Module/Setting Nickname/NicknameViewController.swift
  iOS/Pupago/Pupago/Resource/check.json
Labels: 0_Merge: Dev-iOS

#285 [iOS] Add Alert Sound before Sound To Text
  iOS/Pupago/Pupago.xcodeproj/project.pbxproj
  iOS/Pupago/Pupago/Util/SpeechManager.swift
Labels: 0_Merge: Dev-iOS

#277 [Web] Create roomList page
  client/src/assets/api.ts
  client/src/components/atoms/boxes/RoomItemBox.tsx
  client/src/components/atoms/buttons/MainButton.tsx
  client/src/components/atoms/buttons/RefreshButton.tsx
  client/src/components/molecules/common/RoomItem.tsx
  client/src/components/molecules/roomListPage/MyProfile.tsx
  client/src/components/organisms/roomListPage/EnterCodeButton.tsx
  client/src/components/organisms/roomListPage/MyProfile.tsx
  client/src/components/organisms/roomListPage/RefreshButton.tsx
  client/src/components/organisms/roomListPage/RoomList.tsx
  client/src/modules/roomList.ts
  client/src/pages/MainPage.tsx
  client/src/pages/RoomListPage.tsx
  client/src/utils/timeDisplay.ts
Labels: 0_Merge: Dev-Web, Feature 🎨, Front-end 👩‍💻

#276 [Web] Implement CodeInput page
  client/src/@types/types.ts
  client/src/components/molecules/codeInputPage/CodeInput.tsx
  client/src/components/organisms/codeInputPage/BackButton.tsx
  client/src/components/organisms/codeInputPage/CodeInput.tsx
  client/src/hooks/useRoom.tsx
  client/src/modules/room.ts
  client/src/pages/CodeInputPage.tsx
Labels: 0_Merge: Dev-Web, Feature 🎨, Front-end 👩‍💻

#279 [Web] Implement navigation module and custom hook
  client/src/@types/mainPageNavigation.ts
  client/src/hooks/useNavigation.tsx
  client/src/modules/index.ts
  client/src/modules/navigation.ts
  client/src/pages/MainPage.tsx
  client/src/pages/UserInfoPage.tsx
Labels: 0_Merge: Dev-Web, Feature 🎨, Front-end 👩‍💻

#281 [Web] Create roomCreation page
  client/src/@types/types.ts
  client/src/components/atoms/boxes/CheckBox.tsx
  client/src/components/molecules/RoomCreationPage/RoomCreation.tsx
  client/src/components/organisms/roomCreationPage/BackButton.tsx
  client/src/components/organisms/roomCreationPage/RoomCreation.tsx
  client/src/components/organisms/roomCreationPage/RoomCreationButton.tsx
  client/src/hooks/useRoom.tsx
  client/src/modules/room.ts
  client/src/pages/MainPage.tsx
  client/src/pages/RoomCreationPage.tsx
Labels: 0_Merge: Dev-Web, Feature 🎨, Front-end 👩‍💻

#286 [Web] Implement UserInfoPage
  client/src/components/organisms/userInfoPage/NicknameInput.tsx
  client/src/components/organisms/userInfoPage/StartButtons.tsx
  client/src/pages/UserInfoPage.tsx
Labels: 0_Merge: Dev-Web, Feature 🎨, Front-end 👩‍💻

#287 [Web] Implement room list page
  client/src/components/organisms/roomListPage/CryingPapago.tsx
  client/src/components/organisms/roomListPage/RoomList.tsx
  client/src/components/organisms/roomListPage/RoomListBackButton.tsx
  client/src/modules/roomList.ts
  client/src/pages/RoomListPage.tsx
Labels: Feature 🎨, Front-end 👩‍💻

#290 [iOS] Implement Pulse animation, apply to speech view
  iOS/Pupago/Pupago.xcodeproj/project.pbxproj
  iOS/Pupago/Pupago/Common/Pulsing.swift
  iOS/Pupago/Pupago/Module/SpeechToText/SpeechViewController.swift
Labels: 0_Merge: Dev-iOS

#291 [iOS] Implement Blank Chatroom Situation
  iOS/Pupago/Pupago/Module/Chatting List/ChattingListViewController.swift
  iOS/Pupago/Pupago/Module/Chatting List/ChattingListViewModel.swift
  iOS/Pupago/Pupago/Module/Main/Base.lproj/Main.storyboard
  iOS/Pupago/Pupago/Resource/Assets.xcassets/sadpapago.imageset/Contents.json
  iOS/Pupago/Pupago/Resource/Assets.xcassets/sadpapago.imageset/sadpapago.png
  iOS/Pupago/Pupago/Resource/Localize.swift
Labels: 0_Merge: Dev-iOS

#293 [Web] Implement MainPage
  client/src/components/atoms/buttons/MainButton.tsx
  client/src/components/organisms/codeInputPage/BackButton.tsx
  client/src/components/organisms/roomCreationPage/BackButton.tsx
  client/src/components/organisms/roomCreationPage/RoomCreationButton.tsx
  client/src/components/organisms/roomListPage/CryingPapago.tsx
  client/src/components/organisms/roomListPage/EnterCodeButton.tsx
  client/src/components/organisms/roomListPage/RoomList.tsx
  client/src/components/organisms/roomListPage/RoomListBackButton.tsx
  client/src/components/organisms/userInfoPage/StartButtons.tsx
  client/src/hooks/useNavigation.tsx
  client/src/hooks/useRoom.tsx
  client/src/modules/room.ts
  client/src/pages/MainPage.tsx
  client/src/pages/UserInfoPage.tsx
Labels: 0_Merge: Dev-Web, Feature 🎨, Front-end 👩‍💻

#299 [Web] Create ChatRoomPage's chatLogs
  client/src/components/atoms/boxes/ChatLogsBox.tsx
  client/src/components/atoms/texts/ParticipantNotification.tsx
  client/src/components/molecules/ChatRoomPage/ChatRoomHeader.tsx
  client/src/components/molecules/chatRoomPage/ChatItem.tsx
  client/src/components/organisms/chatPage/ChatHeader.tsx
  client/src/components/organisms/chatPage/ChatLogs.tsx
  client/src/hooks/useChat.tsx
  client/src/pages/ChatPage.tsx
Labels: 0_Merge: Dev-Web, Bug 🐞, Feature 🎨, Front-end 👩‍💻

#296 [iOS] Edit SpeechUI and Animated
  iOS/Pupago/Pupago.xcodeproj/project.pbxproj
  iOS/Pupago/Pupago/Module/Chatting List/ChattingListViewController.swift
  iOS/Pupago/Pupago/Module/Chatting List/ChattingListViewModel.swift
Labels: 0_Merge: Dev-iOS

#301 [iOS] Implement socket life cycle logic, apply to view
  iOS/Pupago/Pupago/Application/Application.swift
  iOS/Pupago/Pupago/Application/SceneDelegate.swift
  iOS/Pupago/Pupago/Module/Chatting List/ChattingListViewModel.swift
  iOS/Pupago/Pupago/Module/Chatting/ChattingViewModel.swift
  iOS/Pupago/Pupago/Module/Setting Nickname/NicknameViewModel.swift
  iOS/Pupago/Pupago/Module/SpeechToText/SpeechViewModel.swift
  iOS/Pupago/Pupago/Resource/Localize.swift
Labels: 0_Merge: Dev-iOS

#302 [Web] Implement ChatRoom sidebar
  client/src/@types/types.ts
  client/src/components/atoms/buttons/RefreshButton.tsx
  client/src/components/molecules/chatRoomPage/SideBar.tsx
  client/src/components/organisms/chatRoomPage/ChatRoomList.tsx
  client/src/components/organisms/chatRoomPage/ParticipantList.tsx
  client/src/components/organisms/chatRoomPage/SideBar.tsx
  client/src/components/organisms/roomListPage/RefreshButton.tsx
  client/src/modules/participantsList.ts
  client/src/pages/ChatPage.tsx
Labels: Feature 🎨, Front-end 👩‍💻

#303 [Web] Fix wrapper css for chatInput
  client/src/components/organisms/chatRoomPage/ChatInput.tsx
  client/src/pages/ChatPage.tsx
Labels: 0_Merge: Dev-Web, Bug 🐞, Front-end 👩‍💻

#304 [Web] Fix socket connection and ChatInput module
  client/src/components/organisms/chatRoomPage/ChatInput.tsx
  client/src/hooks/useChatInput.tsx
  client/src/modules/chatInput.ts
  client/src/pages/ChatPage.tsx
Labels: 0_Merge: Dev-Web, Feature 🎨, Front-end 👩‍💻

#307 [Web] Combine ChatRoomPage
  client/src/App.tsx
  client/src/components/atoms/boxes/ChatLogsBox.tsx
  client/src/components/atoms/boxes/SideBarBox.tsx
  client/src/components/molecules/chatRoomPage/ChatItem.tsx
  client/src/components/organisms/chatRoomPage/ChatHeader.tsx
  client/src/components/organisms/chatRoomPage/ChatInput.tsx
  client/src/components/organisms/chatRoomPage/ChatLogs.tsx
  client/src/components/organisms/chatRoomPage/ChatRoomList.tsx
  client/src/components/organisms/chatRoomPage/ParticipantList.tsx
  client/src/hooks/useUser.tsx
  client/src/modules/user.ts
  client/src/pages/ChatRoomPage.tsx
Labels: 0_Merge: Dev-Web, Feature 🎨, Front-end 👩‍💻

#308 [iOS] Make Up SpeechToText, Apply Animation, Sound and Background Socket Management
  iOS/Pupago/.swiftlint.yml
  iOS/Pupago/Podfile
  iOS/Pupago/Podfile.lock
  iOS/Pupago/Pupago.xcodeproj/project.pbxproj
  iOS/Pupago/Pupago/Application/Application.swift
  iOS/Pupago/Pupago/Application/Navigator.swift
  iOS/Pupago/Pupago/Application/SceneDelegate.swift
  iOS/Pupago/Pupago/Common/Pulsing.swift
  iOS/Pupago/Pupago/Common/SlideInTransition.swift
  iOS/Pupago/Pupago/Common/ValidatingTextField.swift
  iOS/Pupago/Pupago/Common/ViewController.swift
  iOS/Pupago/Pupago/Extensions/KingFisher+Rx.swift
  iOS/Pupago/Pupago/Extensions/UITextView+Binder.swift
  iOS/Pupago/Pupago/Info.plist
  iOS/Pupago/Pupago/Model/Message.swift
  iOS/Pupago/Pupago/Model/Participant.swift
  iOS/Pupago/Pupago/Model/Profile.swift
  iOS/Pupago/Pupago/Module/Chatting List/ChattingListViewController.swift
  iOS/Pupago/Pupago/Module/Chatting List/ChattingListViewModel.swift
  iOS/Pupago/Pupago/Module/Chatting/ChattingViewController.swift
  iOS/Pupago/Pupago/Module/Chatting/ChattingViewModel.swift
  iOS/Pupago/Pupago/Module/Chatting/MessageDataSource.swift
  iOS/Pupago/Pupago/Module/Chatting/MyChattingCell.swift
  iOS/Pupago/Pupago/Module/Chatting/OthersChattingCell.swift
  iOS/Pupago/Pupago/Module/Join Chatroom/JoinRoomViewModel.swift
  iOS/Pupago/Pupago/Module/Main/Base.lproj/Main.storyboard
  iOS/Pupago/Pupago/Module/Participant/ParticipantCell.swift
  iOS/Pupago/Pupago/Module/Participant/ParticipantViewController.swift
  iOS/Pupago/Pupago/Module/Participant/ParticipantViewModel.swift
  iOS/Pupago/Pupago/Module/Setting Language/LanguageViewController.swift
  iOS/Pupago/Pupago/Module/Setting Nickname/NicknameViewController.swift
  iOS/Pupago/Pupago/Module/Setting Nickname/NicknameViewModel.swift
  iOS/Pupago/Pupago/Module/SpeechToText/SpeechViewController.swift
  iOS/Pupago/Pupago/Module/SpeechToText/SpeechViewModel.swift
  iOS/Pupago/Pupago/Network/Endpoint/RoomEndpoint.swift
  iOS/Pupago/Pupago/Network/NetworkProviding.swift
  iOS/Pupago/Pupago/Network/Service/PupagoAPI.swift
  iOS/Pupago/Pupago/Network/SocketManager.swift
  iOS/Pupago/Pupago/Resource/Assets.xcassets/arrow.imageset/Contents.json
  iOS/Pupago/Pupago/Resource/Assets.xcassets/arrow.imageset/arrow.png
  iOS/Pupago/Pupago/Resource/Assets.xcassets/arrowed.imageset/Contents.json
  iOS/Pupago/Pupago/Resource/Assets.xcassets/arrowed.imageset/arrowed.png
  iOS/Pupago/Pupago/Resource/Assets.xcassets/miced.imageset/Contents.json
  iOS/Pupago/Pupago/Resource/Assets.xcassets/miced.imageset/miced.png
  iOS/Pupago/Pupago/Resource/Assets.xcassets/micing.imageset/Contents.json
  iOS/Pupago/Pupago/Resource/Assets.xcassets/micing.imageset/micing.png
  iOS/Pupago/Pupago/Resource/Assets.xcassets/sadpapago.imageset/Contents.json
  iOS/Pupago/Pupago/Resource/Assets.xcassets/sadpapago.imageset/sadpapago.png
  iOS/Pupago/Pupago/Resource/Localize.swift
  iOS/Pupago/Pupago/Resource/check.json
  iOS/Pupago/Pupago/Util/SpeechManager.swift
  iOS/Pupago/Pupago/Util/TransitionHelper.swift
  iOS/Pupago/Pupago/Util/Translator.swift
Labels: 0_Merge: Dev

#310 [Web] Add socket to user module and connect only once
  client/src/components/organisms/chatRoomPage/ChatInput.tsx
  client/src/hooks/useUser.tsx
  client/src/modules/user.ts
  client/src/pages/ChatRoomPage.tsx
Labels: 0_Merge: Dev-Web, Feature 🎨, Front-end 👩‍💻

#309 [Web] Update codeInput validation Logic
  client/src/components/organisms/codeInputPage/CodeInput.tsx
Labels: Feature 🎨, Front-end 👩‍💻

#312 [Web] Reset states when leave chatroom or close window
  client/src/components/atoms/texts/ParticipantNotification.tsx
  client/src/components/organisms/chatRoomPage/ChatHeader.tsx
  client/src/components/organisms/chatRoomPage/ChatInput.tsx
  client/src/components/organisms/chatRoomPage/ChatLogs.tsx
  client/src/hooks/useChat.tsx
  client/src/hooks/useChatInput.tsx
  client/src/hooks/useParticipantsList.tsx
  client/src/hooks/useUser.tsx
  client/src/modules/chat.ts
  client/src/modules/chatInput.ts
  client/src/modules/participantsList.ts
  client/src/modules/user.ts
  client/src/pages/ChatRoomPage.tsx
  client/src/pages/MainPage.tsx
  client/src/pages/UserInfoPage.tsx
Labels: 0_Merge: Dev-Web, Bug 🐞, Feature 🎨, Front-end 👩‍💻, Refactor ⚙️

#314 [Web] Validate nickname and room title
  client/src/components/organisms/roomCreationPage/RoomCreationButton.tsx
  client/src/components/organisms/userInfoPage/NicknameInput.tsx
  client/src/components/organisms/userInfoPage/StartButtons.tsx
Labels: 0_Merge: Dev-Web, Feature 🎨, Front-end 👩‍💻

#316 [Web] Add voice recognition and its modal UI
  client/package-lock.json
  client/package.json
  client/src/components/organisms/chatRoomPage/ChatInput.tsx
  client/src/components/organisms/chatRoomPage/VoiceRecognition.tsx
  client/src/hooks/useChatInput.tsx
Labels: 0_Merge: Dev-Web, Feature 🎨, Front-end 👩‍💻

#323 [Web] Set chatlogs scroll bar to focus bottom
  client/src/components/organisms/chatRoomPage/ChatLogs.tsx
  client/src/pages/ChatRoomPage.tsx
Labels: 0_Merge: Dev-Web, Feature 🎨, Front-end 👩‍💻

#321 [Web] Fix erase too fast problem and not debounced problem
  client/src/components/organisms/chatRoomPage/ChatInput.tsx
  client/src/hooks/useChatInput.tsx
  client/src/modules/chatInput.ts
Labels: 0_Merge: Dev-Web, Feature 🎨, Front-end 👩‍💻

#324 [Web] Fix conflict errors
  client/src/components/organisms/chatRoomPage/ChatInput.tsx
  client/src/modules/chatInput.ts
Labels: 0_Merge: Dev-Web, Bug 🐞, Feature 🎨

#325 [Web] Join chatRoom when create room
  client/src/components/organisms/roomCreationPage/RoomCreationButton.tsx
Labels: 0_Merge: Dev-Web, Feature 🎨, Front-end 👩‍💻

#335 [Web] Upgrade socket.io-client
  client/package-lock.json
  client/package.json
Labels: 0_Merge: Dev-Web, Bug 🐞, Environment 🌏, Front-end 👩‍💻

#330 [Web] Enable room switching from the room list inside chat room page
  client/src/@types/types.ts
  client/src/App.tsx
  client/src/components/atoms/buttons/MainButton.tsx
  client/src/components/molecules/ChatRoomPage/RoomSwitchModal.tsx
  client/src/components/organisms/chatRoomPage/ChatRoomList.tsx
  client/src/hooks/useReset.tsx
  client/src/hooks/useRoom.tsx
  client/src/modules/room.ts
  client/src/pages/SwitchRoomLoadingPage.tsx
Labels: 0_Merge: Dev-Web, Feature 🎨, Front-end 👩‍💻

#331 [Web] Fix roomlist spacing
  client/src/components/atoms/boxes/ChatLogsBox.tsx
  client/src/components/atoms/boxes/RoomItemBox.tsx
  client/src/components/molecules/chatRoomPage/SideBar.tsx
Labels: 0_Merge: Dev-Web, Feature 🎨, Front-end 👩‍💻

#327 [Web] Block participation in chat room when room entry is maximum
  server/src/@types/maxParticipantsInRoom.ts
  server/src/controllers/joinController.ts
  server/src/utils/validation.ts
Labels: 0_Merge: Dev-Web, Back-End 👨‍💻, Bug 🐞

#337 [Web] Fix time display as 'created now' when time elapsed is below 10 seconds
  client/src/components/organisms/.gitkeep
  client/src/utils/.gitkeep
  client/src/utils/timeDisplay.ts
Labels: 0_Merge: Dev-Web, Bug 🐞, Front-end 👩‍💻

#338 [Web] Fix ChatInput Error
  client/src/components/organisms/chatRoomPage/ChatInput.tsx
  client/src/hooks/useChatInput.tsx
  client/src/modules/chatInput.ts
Labels: 0_Merge: Dev-Web, Bug 🐞, Front-end 👩‍💻

#340 [Web] Limit ChatInput's max length
  client/src/@types/characterLimit.ts
  client/src/components/molecules/chatRoomPage/ChatInput.tsx
  client/src/hooks/useChatInput.tsx
Labels: 0_Merge: Dev-Web, Bug 🐞, Front-end 👩‍💻

#342 [Web] Stop changing profile Photo when come back to user ProfilePage
  client/src/components/organisms/userInfoPage/ProfilePictureSelection.tsx
Labels: 0_Merge: Dev-Web, Bug 🐞, Front-end 👩‍💻

#344 [Web] Alert when code input is not valid, and change URL when code input is valid
  client/src/components/organisms/codeInputPage/CodeInput.tsx
Labels: Feature 🎨, Front-end 👩‍💻

#346 [iOS] Implement Image OCR
  iOS/Pupago/Pupago.xcodeproj/project.pbxproj
  iOS/Pupago/Pupago/Application/Navigator.swift
  iOS/Pupago/Pupago/Common/ViewController.swift
  iOS/Pupago/Pupago/Extensions/AnimationView+Binder.swift
  iOS/Pupago/Pupago/Extensions/UIImage+Base64.swift
  iOS/Pupago/Pupago/Extensions/UILabel+Binder.swift
  iOS/Pupago/Pupago/Extensions/VNDocumentCameraViewController+Rx.swift
  iOS/Pupago/Pupago/Info.plist
  iOS/Pupago/Pupago/Model/OCR.swift
  iOS/Pupago/Pupago/Module/Chatting/ChattingViewController.swift
  iOS/Pupago/Pupago/Module/Chatting/ChattingViewModel.swift
  iOS/Pupago/Pupago/Module/Main/Base.lproj/Main.storyboard
  iOS/Pupago/Pupago/Module/OCR/ScanningViewController.swift
  iOS/Pupago/Pupago/Module/OCR/ScanningViewModel.swift
  iOS/Pupago/Pupago/Network/Endpoint/ClovaEndpoint.swift
  iOS/Pupago/Pupago/Network/Service/PupagoAPI.swift
  iOS/Pupago/Pupago/Resource/Assets.xcassets/1200px--Portable_scanner_and_OCR_(video).webm.imageset/1200px--Portable_scanner_and_OCR_(video).webm.jpg
  iOS/Pupago/Pupago/Resource/Assets.xcassets/1200px--Portable_scanner_and_OCR_(video).webm.imageset/Contents.json
  iOS/Pupago/Pupago/Resource/Localize.swift
  iOS/Pupago/Pupago/Resource/scanning.json
  iOS/Pupago/Pupago/Util/DateManager.swift
Labels: 0_Merge: Dev-iOS, iOS 🍎

#352 [Web] Copy to clipboard when click room code
  client/src/components/molecules/chatRoomPage/ChatRoomHeader.tsx
  client/src/components/organisms/chatRoomPage/ChatHeader.tsx
Labels: 0_Merge: Dev-Web, Feature 🎨, Front-end 👩‍💻

#354 [Web] Make alert before leave
  client/src/App.tsx
Labels: 0_Merge: Dev-Web, Feature 🎨, Front-end 👩‍💻

#357 [Web] Fix CodeInput error when code is not valid
  client/src/@types/characterLimit.ts
  client/src/components/organisms/codeInputPage/CodeInput.tsx
Labels: 0_Merge: Dev-Web, Bug 🐞, Front-end 👩‍💻

#355 [Web] Move room switch modal to SideBar organism
  client/src/components/organisms/chatRoomPage/ChatRoomList.tsx
  client/src/components/organisms/chatRoomPage/SideBar.tsx
Labels: 0_Merge: Dev-Web, Feature 🎨, Front-end 👩‍💻

#359 [Web] Add language option to voice recognition
  client/src/components/organisms/chatRoomPage/VoiceRecognition.tsx
Labels: 0_Merge: Dev-Web, Feature 🎨, Front-end 👩‍💻

#368 [Web] Add input error signal to the nickname input and refactor it to a molecule
  client/src/@types/characterLimit.ts
  client/src/components/atoms/inputs/UnderLinedInput.tsx
  client/src/components/molecules/userInfoPage/NicknameInput.tsx
  client/src/components/organisms/userInfoPage/NicknameInput.tsx
Labels: 0_Merge: Dev-Web, Feature 🎨, Front-end 👩‍💻

#372 [Web] Place myself at top of the participants list
  client/src/components/organisms/chatRoomPage/ParticipantList.tsx
  client/src/modules/participantsList.ts
Labels: 0_Merge: Dev-Web, Feature 🎨, Front-end 👩‍💻

#371 [Web] Sort room lists in descending order
  client/src/modules/roomList.ts
Labels: 0_Merge: Dev-Web, Feature 🎨, Front-end 👩‍💻

#361 [Web] Disable a button to enter the room full of participants
  client/src/@types/participantsLimit.ts
  client/src/components/atoms/boxes/RoomItemBox.tsx
  client/src/components/molecules/common/RoomItem.tsx
  client/src/components/organisms/roomListPage/RoomList.tsx
Labels: 0_Merge: Dev-Web, Feature 🎨, Front-end 👩‍💻

#363 [Web] Reduce the size of iconButton div
  client/src/components/atoms/buttons/IconButton.tsx
Labels: 0_Merge: Dev-Web, Bug 🐞, Front-end 👩‍💻

#369 [Web] Implement react-intl to the project and make example to use it
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/assets/.gitkeep
  client/src/assets/locale/en.ts
  client/src/assets/locale/ko.ts
  client/src/components/atoms/texts/ParticipantNotification.tsx
Labels: 0_Merge: Dev-Web, Feature 🎨, Front-end 👩‍💻

#373 [Web] Fix Warning at console for readOnly property
  client/src/components/molecules/chatRoomPage/ChatRoomHeader.tsx
Labels: 0_Merge: Dev-Web, Bug 🐞, Front-end 👩‍💻

#374 [Web] Fix error about langCode
  client/src/App.tsx
Labels: Bug 🐞, Front-end 👩‍💻

#375 [Web] Fix socket disconnection error when switching room
  client/src/components/organisms/chatRoomPage/SideBar.tsx
  client/src/hooks/useReset.tsx
Labels: 0_Merge: Dev-Web, Feature 🎨, Front-end 👩‍💻

#379 [Web] Change Static string to intl string
  client/src/assets/locale/en.ts
  client/src/assets/locale/ko.ts
  client/src/components/atoms/texts/ParticipantNotification.tsx
  client/src/components/molecules/chatRoomPage/RoomSwitchModal.tsx
  client/src/components/molecules/chatRoomPage/SideBar.tsx
  client/src/components/molecules/codeInputPage/CodeInput.tsx
  client/src/components/molecules/roomCreationPage/RoomCreation.tsx
  client/src/components/molecules/roomListPage/NoChatRoom.tsx
  client/src/components/molecules/userInfoPage/LanguageSelection.tsx
  client/src/components/molecules/userInfoPage/MainTitle.tsx
  client/src/components/molecules/userInfoPage/NicknameInput.tsx
  client/src/components/organisms/chatRoomPage/ChatHeader.tsx
  client/src/components/organisms/codeInputPage/CodeInput.tsx
  client/src/components/organisms/roomListPage/CryingPapago.tsx
  client/src/components/organisms/roomListPage/EnterCodeButton.tsx
  client/src/components/organisms/userInfoPage/StartButtons.tsx
Labels: 0_Merge: Dev-Web, Feature 🎨, Front-end 👩‍💻

#381 [Web] Apply https to server
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/src/loaders/option.ts
Labels: 0_Merge: Dev-Web, Back-End 👨‍💻, Environment 🌏
